#!/usr/bin/env python3
"""Generate nebbie-core special proc name catalog from Nebbie server sources."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OTHER_SRC = ROOT / "vendor" / "nebbietest" / "src" / "specialproc_other.cpp"
ROOM_SRC = ROOT / "vendor" / "nebbietest" / "src" / "specialproc_room.cpp"
OUT_CPP = ROOT / "nebbie-core" / "src" / "special_proc_catalog_data.cpp"

ENTRY_RE = re.compile(r'\{\s*"([^"]+)"\s*,')


def extract_names(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    return sorted(set(ENTRY_RE.findall(text)))


def emit_cpp(other_names: list[str], room_names: list[str]) -> str:
    lines = [
        "// Generated by scripts/generate-special-proc-catalog.py — do not edit.",
        '#include "nebbie/special_proc_catalog.hpp"',
        "",
        "namespace nebbie {",
        "",
        "namespace {",
        "",
        "const char* kMobObjectSpecialProcNames[] = {",
    ]
    for name in other_names:
        lines.append(f'    "{name}",')
    lines.extend(
        [
            "};",
            "",
            "const char* kRoomSpecialProcNames[] = {",
        ]
    )
    for name in room_names:
        lines.append(f'    "{name}",')
    lines.extend(
        [
            "};",
            "",
            "} // namespace",
            "",
            "const std::vector<std::string>& mob_object_special_proc_names() {",
            "    static const std::vector<std::string> names = [] {",
            "        std::vector<std::string> out;",
            f"        out.reserve({len(other_names)});",
            "        for (const char* name : kMobObjectSpecialProcNames) {",
            "            out.emplace_back(name);",
            "        }",
            "        return out;",
            "    }();",
            "    return names;",
            "}",
            "",
            "const std::vector<std::string>& room_special_proc_names() {",
            "    static const std::vector<std::string> names = [] {",
            "        std::vector<std::string> out;",
            f"        out.reserve({len(room_names)});",
            "        for (const char* name : kRoomSpecialProcNames) {",
            "            out.emplace_back(name);",
            "        }",
            "        return out;",
            "    }();",
            "    return names;",
            "}",
            "",
            "} // namespace nebbie",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if not OTHER_SRC.is_file() or not ROOM_SRC.is_file():
        raise SystemExit(f"Server sources not found under {ROOT / 'vendor' / 'nebbietest'}")

    other_names = extract_names(OTHER_SRC)
    room_names = extract_names(ROOM_SRC)
    if not other_names or not room_names:
        raise SystemExit("No special proc names extracted")

    OUT_CPP.write_text(emit_cpp(other_names, room_names), encoding="utf-8")
    print(f"Wrote {OUT_CPP} ({len(other_names)} mob/object, {len(room_names)} room)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
